let cat = new Cat("Bob",GENDER.MALE,FOOD.FISH);
cat.Move();
cat.Sleep();
Cat.Catch_Mouse(cat.Name);
let cat2 = new Cat("Suzy",GENDER.FEMALE,FOOD.PORK);
Cat.Compare_night_vision(cat.Night_vision_point,cat.Name,cat2.Night_vision_point,cat2.Name);
cat.Eat();
cat.Check_Status();
let cow = new Cow("Lulu",GENDER.FEMALE,FOOD.GRASS);
cow.Make_Sound();